/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorAltaComunidad;
import Controlador.ControladorScanner;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;

/**
 *
 * @author varga
 */
public class AltaComunidad extends javax.swing.JPanel {

    /**
     * Creates new form AltaUsuario
     */
    ControladorAltaComunidad controlador;
    public CardLayout vistaDinamica;

    public AltaComunidad(ControladorScanner controladorScanner) {
        initComponents();
        vistaDinamica = (CardLayout)panelDinamico.getLayout();
        controlador = new ControladorAltaComunidad(this,controladorScanner);
        this.comboTipo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        kGradientPanel1 = new keeptoo.KGradientPanel();
        comboTipo = new javax.swing.JComboBox<>();
        etiquetaIcono = new javax.swing.JLabel();
        etiquetaUltimoRegistro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelDinamico = new javax.swing.JPanel();

        setBackground(new java.awt.Color(210, 231, 255));
        setLayout(new java.awt.GridBagLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(0, 120));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(0, 120));
        kGradientPanel1.setLayout(new java.awt.GridBagLayout());

        comboTipo.setBackground(new java.awt.Color(210, 231, 255));
        comboTipo.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        comboTipo.setForeground(new java.awt.Color(102, 100, 200));
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente", "Visitante" }));
        comboTipo.setBorder(null);
        comboTipo.setEditor(null);
        comboTipo.setMinimumSize(new java.awt.Dimension(200, 30));
        comboTipo.setPreferredSize(new java.awt.Dimension(200, 30));
        comboTipo.setRenderer(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(65, 10, 65, 40);
        kGradientPanel1.add(comboTipo, gridBagConstraints);

        etiquetaIcono.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        etiquetaIcono.setText("icono");
        etiquetaIcono.setMinimumSize(new java.awt.Dimension(0, 0));
        etiquetaIcono.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        kGradientPanel1.add(etiquetaIcono, gridBagConstraints);

        etiquetaUltimoRegistro.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaUltimoRegistro.setText("<html><leading>Último registro:");
        etiquetaUltimoRegistro.setMinimumSize(new java.awt.Dimension(0, 0));
        etiquetaUltimoRegistro.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 10);
        kGradientPanel1.add(etiquetaUltimoRegistro, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Seleccione tipo:");
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        kGradientPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        add(kGradientPanel1, gridBagConstraints);

        panelDinamico.setPreferredSize(new java.awt.Dimension(0, 0));
        panelDinamico.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        add(panelDinamico, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel etiquetaIcono;
    private javax.swing.JLabel etiquetaUltimoRegistro;
    private javax.swing.JLabel jLabel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    public javax.swing.JPanel panelDinamico;
    // End of variables declaration//GEN-END:variables
}