/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorAltaAlumno;
import Controlador.ControladorDiseñoBoton;
import Controlador.ObtenerComponentes;
import javax.swing.JLabel;

/**
 *
 * @author varga
 */
public class AltaAlumno extends javax.swing.JPanel {

    /**
     * Creates new form AltaAlumno
     */
    ControladorAltaAlumno controlador;
    ControladorDiseñoBoton d;
    ObtenerComponentes c;
    public AltaAlumno() {
        initComponents();
        controlador = new ControladorAltaAlumno(this);
        c = new ObtenerComponentes();
        d = new ControladorDiseñoBoton(c.obtenerBotones(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox<>();
        comboAño = new javax.swing.JComboBox<>();
        cajaApMaterno = new javax.swing.JTextField();
        cajaApPaterno = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        etiquetaMatricula = new javax.swing.JLabel();
        etiquetaFacultad1 = new javax.swing.JLabel();
        etiquetaLicenciatura1 = new javax.swing.JLabel();
        etiquetaLicenciatura2 = new javax.swing.JLabel();
        comboSemestre = new javax.swing.JComboBox<>();
        comboLicenciatura = new javax.swing.JComboBox<>();
        comboFacultad1 = new javax.swing.JComboBox<Object>();
        cajaMatricula = new javax.swing.JTextField();
        guardarAlumno = new javax.swing.JButton();
        etiquetaValidacion = new javax.swing.JLabel();
        etiquetaSexo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 231, 255));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.GridBagLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(68, 184, 194));
        kGradientPanel1.setkStartColor(new java.awt.Color(66, 132, 188));
        kGradientPanel1.setLayout(new java.awt.GridBagLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(210, 231, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(210, 231, 255));
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(250, 30));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(250, 30));
        kGradientPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(70, 50, 20, 6);
        kGradientPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido paterno: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        kGradientPanel2.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido materno: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        kGradientPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Año de nacimiento:");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        kGradientPanel2.add(jLabel5, gridBagConstraints);

        comboSexo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboSexo.setMinimumSize(new java.awt.Dimension(250, 30));
        comboSexo.setName("licenciatura"); // NOI18N
        comboSexo.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 50, 6);
        kGradientPanel2.add(comboSexo, gridBagConstraints);

        comboAño.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboAño.setMinimumSize(new java.awt.Dimension(250, 30));
        comboAño.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        kGradientPanel2.add(comboAño, gridBagConstraints);

        cajaApMaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        cajaApMaterno.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaApMaterno.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        kGradientPanel2.add(cajaApMaterno, gridBagConstraints);

        cajaApPaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        cajaApPaterno.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaApPaterno.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        kGradientPanel2.add(cajaApPaterno, gridBagConstraints);

        cajaNombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        cajaNombre.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaNombre.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(70, 5, 20, 6);
        kGradientPanel2.add(cajaNombre, gridBagConstraints);

        etiquetaMatricula.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaMatricula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaMatricula.setText("Matrícula:");
        etiquetaMatricula.setMaximumSize(new java.awt.Dimension(150, 30));
        etiquetaMatricula.setMinimumSize(new java.awt.Dimension(150, 30));
        etiquetaMatricula.setName("alumno"); // NOI18N
        etiquetaMatricula.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(70, 5, 20, 6);
        kGradientPanel2.add(etiquetaMatricula, gridBagConstraints);

        etiquetaFacultad1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaFacultad1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaFacultad1.setText("Facultad:");
        etiquetaFacultad1.setMaximumSize(new java.awt.Dimension(150, 30));
        etiquetaFacultad1.setMinimumSize(new java.awt.Dimension(150, 30));
        etiquetaFacultad1.setName("alumno"); // NOI18N
        etiquetaFacultad1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        kGradientPanel2.add(etiquetaFacultad1, gridBagConstraints);

        etiquetaLicenciatura1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaLicenciatura1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaLicenciatura1.setText("Licenciatura:");
        etiquetaLicenciatura1.setMaximumSize(new java.awt.Dimension(150, 30));
        etiquetaLicenciatura1.setMinimumSize(new java.awt.Dimension(150, 30));
        etiquetaLicenciatura1.setName("alumno"); // NOI18N
        etiquetaLicenciatura1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        kGradientPanel2.add(etiquetaLicenciatura1, gridBagConstraints);

        etiquetaLicenciatura2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaLicenciatura2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaLicenciatura2.setText("Semestre:");
        etiquetaLicenciatura2.setMaximumSize(new java.awt.Dimension(150, 30));
        etiquetaLicenciatura2.setMinimumSize(new java.awt.Dimension(150, 30));
        etiquetaLicenciatura2.setName("alumno"); // NOI18N
        etiquetaLicenciatura2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        kGradientPanel2.add(etiquetaLicenciatura2, gridBagConstraints);

        comboSemestre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        comboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboSemestre.setMinimumSize(new java.awt.Dimension(250, 30));
        comboSemestre.setName("licenciatura"); // NOI18N
        comboSemestre.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        kGradientPanel2.add(comboSemestre, gridBagConstraints);

        comboLicenciatura.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        comboLicenciatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboLicenciatura.setMinimumSize(new java.awt.Dimension(250, 30));
        comboLicenciatura.setName("licenciatura"); // NOI18N
        comboLicenciatura.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        kGradientPanel2.add(comboLicenciatura, gridBagConstraints);

        comboFacultad1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        comboFacultad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboFacultad1.setMinimumSize(new java.awt.Dimension(250, 30));
        comboFacultad1.setName("alumno"); // NOI18N
        comboFacultad1.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        kGradientPanel2.add(comboFacultad1, gridBagConstraints);

        cajaMatricula.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        cajaMatricula.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaMatricula.setName("alumno"); // NOI18N
        cajaMatricula.setPreferredSize(new java.awt.Dimension(250, 30));
        cajaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaMatriculaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(70, 5, 20, 6);
        kGradientPanel2.add(cajaMatricula, gridBagConstraints);

        guardarAlumno.setBackground(new java.awt.Color(84, 125, 200));
        guardarAlumno.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        guardarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        guardarAlumno.setText("  Guardar ");
        guardarAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        guardarAlumno.setBorderPainted(false);
        guardarAlumno.setContentAreaFilled(false);
        guardarAlumno.setHideActionText(true);
        guardarAlumno.setMaximumSize(new java.awt.Dimension(160, 50));
        guardarAlumno.setMinimumSize(new java.awt.Dimension(160, 50));
        guardarAlumno.setName("alumno"); // NOI18N
        guardarAlumno.setOpaque(true);
        guardarAlumno.setPreferredSize(new java.awt.Dimension(160, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        kGradientPanel2.add(guardarAlumno, gridBagConstraints);

        etiquetaValidacion.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        etiquetaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaValidacion.setMaximumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setMinimumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(70, 5, 20, 6);
        kGradientPanel2.add(etiquetaValidacion, gridBagConstraints);

        etiquetaSexo1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaSexo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaSexo1.setText("Sexo:");
        etiquetaSexo1.setMaximumSize(new java.awt.Dimension(150, 30));
        etiquetaSexo1.setMinimumSize(new java.awt.Dimension(150, 30));
        etiquetaSexo1.setName("alumno"); // NOI18N
        etiquetaSexo1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 50, 6);
        kGradientPanel2.add(etiquetaSexo1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        kGradientPanel1.add(kGradientPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(kGradientPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cajaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaMatriculaActionPerformed
public void setConfirmacion(JLabel etiquetaConfirmacion) {
        controlador.setConfirmacion(etiquetaConfirmacion);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cajaApMaterno;
    public javax.swing.JTextField cajaApPaterno;
    public javax.swing.JTextField cajaMatricula;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JComboBox<String> comboAño;
    public javax.swing.JComboBox<Object> comboFacultad1;
    public javax.swing.JComboBox<Object> comboLicenciatura;
    public javax.swing.JComboBox<Object> comboSemestre;
    public javax.swing.JComboBox<Object> comboSexo;
    public javax.swing.JLabel etiquetaFacultad1;
    public javax.swing.JLabel etiquetaLicenciatura1;
    public javax.swing.JLabel etiquetaLicenciatura2;
    public javax.swing.JLabel etiquetaMatricula;
    public javax.swing.JLabel etiquetaSexo1;
    public javax.swing.JLabel etiquetaValidacion;
    public javax.swing.JButton guardarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
