/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorAltaDocente;
import Controlador.ControladorScanner;

/**
 *
 * @author varga
 */
public class AltaDocente extends javax.swing.JPanel {

    /**
     * Creates new form altaDocente
     */
    ControladorAltaDocente controlador;

    public AltaDocente(ControladorScanner controladorScanner) {
        initComponents();
        controlador = new ControladorAltaDocente(this, controladorScanner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiquetaSexo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox<>();
        comboAño = new javax.swing.JComboBox<>();
        cajaApMaterno = new javax.swing.JTextField();
        cajaApPaterno = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        etiquetaMatricula = new javax.swing.JLabel();
        cajaNoPlaza = new javax.swing.JTextField();
        guardarAlumno = new javax.swing.JButton();
        etiquetaValidacion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 231, 255));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido paterno: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido materno: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Año de nacimiento:");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 20, 6);
        add(jLabel5, gridBagConstraints);

        etiquetaSexo.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaSexo.setText("Sexo:");
        etiquetaSexo.setMaximumSize(new java.awt.Dimension(150, 30));
        etiquetaSexo.setMinimumSize(new java.awt.Dimension(150, 30));
        etiquetaSexo.setName("alumno"); // NOI18N
        etiquetaSexo.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 100, 6);
        add(etiquetaSexo, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(100, 50, 20, 6);
        add(jLabel1, gridBagConstraints);

        comboSexo.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboSexo.setMinimumSize(new java.awt.Dimension(250, 30));
        comboSexo.setName("licenciatura"); // NOI18N
        comboSexo.setPreferredSize(new java.awt.Dimension(250, 30));
        comboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSexoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 100, 6);
        add(comboSexo, gridBagConstraints);

        comboAño.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboAño.setMinimumSize(new java.awt.Dimension(250, 30));
        comboAño.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        add(comboAño, gridBagConstraints);

        cajaApMaterno.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaApMaterno.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        add(cajaApMaterno, gridBagConstraints);

        cajaApPaterno.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaApPaterno.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 6);
        add(cajaApPaterno, gridBagConstraints);

        cajaNombre.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaNombre.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 20, 6);
        add(cajaNombre, gridBagConstraints);

        etiquetaMatricula.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        etiquetaMatricula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaMatricula.setText("No.Plaza:");
        etiquetaMatricula.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaMatricula.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaMatricula.setName("alumno"); // NOI18N
        etiquetaMatricula.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 20, 6);
        add(etiquetaMatricula, gridBagConstraints);

        cajaNoPlaza.setMinimumSize(new java.awt.Dimension(250, 30));
        cajaNoPlaza.setName("alumno"); // NOI18N
        cajaNoPlaza.setPreferredSize(new java.awt.Dimension(250, 30));
        cajaNoPlaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNoPlazaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 20, 6);
        add(cajaNoPlaza, gridBagConstraints);

        guardarAlumno.setBackground(new java.awt.Color(152, 219, 175));
        guardarAlumno.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        guardarAlumno.setText("  Guardar ");
        guardarAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        guardarAlumno.setBorderPainted(false);
        guardarAlumno.setContentAreaFilled(false);
        guardarAlumno.setHideActionText(true);
        guardarAlumno.setMaximumSize(new java.awt.Dimension(160, 50));
        guardarAlumno.setMinimumSize(new java.awt.Dimension(160, 50));
        guardarAlumno.setName("alumno"); // NOI18N
        guardarAlumno.setOpaque(true);
        guardarAlumno.setPreferredSize(new java.awt.Dimension(160, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        add(guardarAlumno, gridBagConstraints);

        etiquetaValidacion.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        etiquetaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaValidacion.setMaximumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setMinimumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 20, 6);
        add(etiquetaValidacion, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cajaNoPlazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNoPlazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNoPlazaActionPerformed

    private void comboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSexoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cajaApMaterno;
    public javax.swing.JTextField cajaApPaterno;
    public javax.swing.JTextField cajaNoPlaza;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JComboBox<String> comboAño;
    public javax.swing.JComboBox<Object> comboSexo;
    public javax.swing.JLabel etiquetaMatricula;
    public javax.swing.JLabel etiquetaSexo;
    public javax.swing.JLabel etiquetaValidacion;
    public javax.swing.JButton guardarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
