/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorScanner;
import Controlador.controladorConsultaUsuario;

/**
 *
 * @author varga
 */
public class ConsultaUsuario extends javax.swing.JPanel {

    /**
     * Creates new form consultaUsuarios
     */
    controladorConsultaUsuario controlador;

    public ConsultaUsuario(ControladorScanner controladorScanner) {
        initComponents();
        controlador = new controladorConsultaUsuario(this, controladorScanner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        etiquetaClave = new javax.swing.JLabel();
        comboFiltrarPor = new javax.swing.JComboBox<>();
        cajaBuscarClave = new javax.swing.JTextField();
        cajaBuscarPor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        panelOpciones = new javax.swing.JPanel();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonDetalle = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 231, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 200));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        etiquetaClave.setBackground(new java.awt.Color(32, 32, 32));
        etiquetaClave.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        etiquetaClave.setText("      Buscar ID:");
        etiquetaClave.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(etiquetaClave, gridBagConstraints);

        comboFiltrarPor.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        comboFiltrarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por...", "Alumno", "Docente", "Visitante" }));
        comboFiltrarPor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        comboFiltrarPor.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(comboFiltrarPor, gridBagConstraints);

        cajaBuscarClave.setBorder(null);
        cajaBuscarClave.setMinimumSize(new java.awt.Dimension(160, 30));
        cajaBuscarClave.setPreferredSize(new java.awt.Dimension(160, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(cajaBuscarClave, gridBagConstraints);

        cajaBuscarPor.setBorder(null);
        cajaBuscarPor.setMinimumSize(new java.awt.Dimension(160, 30));
        cajaBuscarPor.setPreferredSize(new java.awt.Dimension(160, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(cajaBuscarPor, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(32, 32, 32));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        jLabel2.setText("      Buscar por:");
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 880;
        gridBagConstraints.ipady = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(133, 10, 0, 10);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(210, 231, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 350));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 350));

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Ap,Paterno", "Ap.Materno", "Edad", "Sexo", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonas.setRowHeight(50);
        tablaPersonas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaPersonas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        panelOpciones.setBackground(new java.awt.Color(196, 229, 174));
        panelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 0, 18), new java.awt.Color(240, 240, 240))), "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 0, 18))); // NOI18N
        panelOpciones.setForeground(new java.awt.Color(240, 240, 240));
        panelOpciones.setMinimumSize(new java.awt.Dimension(160, 200));
        panelOpciones.setPreferredSize(new java.awt.Dimension(160, 200));
        panelOpciones.setLayout(new java.awt.GridBagLayout());

        botonEditar.setBackground(new java.awt.Color(152, 219, 175));
        botonEditar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        botonEditar.setBorderPainted(false);
        botonEditar.setContentAreaFilled(false);
        botonEditar.setMinimumSize(new java.awt.Dimension(156, 40));
        botonEditar.setOpaque(true);
        botonEditar.setPreferredSize(new java.awt.Dimension(156, 40));
        botonEditar.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelOpciones.add(botonEditar, gridBagConstraints);

        botonEliminar.setBackground(new java.awt.Color(152, 219, 175));
        botonEliminar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        botonEliminar.setText("Eliminar  ");
        botonEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        botonEliminar.setBorderPainted(false);
        botonEliminar.setContentAreaFilled(false);
        botonEliminar.setMinimumSize(new java.awt.Dimension(156, 40));
        botonEliminar.setOpaque(true);
        botonEliminar.setPreferredSize(new java.awt.Dimension(156, 40));
        botonEliminar.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelOpciones.add(botonEliminar, gridBagConstraints);

        botonDetalle.setBackground(new java.awt.Color(152, 219, 175));
        botonDetalle.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        botonDetalle.setText("Detalle");
        botonDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        botonDetalle.setBorderPainted(false);
        botonDetalle.setContentAreaFilled(false);
        botonDetalle.setMinimumSize(new java.awt.Dimension(156, 40));
        botonDetalle.setOpaque(true);
        botonDetalle.setPreferredSize(new java.awt.Dimension(156, 40));
        botonDetalle.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelOpciones.add(botonDetalle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(panelOpciones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.ipady = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 133, 10);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonDetalle;
    public javax.swing.JButton botonEditar;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JTextField cajaBuscarClave;
    public javax.swing.JTextField cajaBuscarPor;
    public javax.swing.JComboBox<String> comboFiltrarPor;
    public javax.swing.JLabel etiquetaClave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelOpciones;
    public javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables
}
