/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorDiseñoBoton;
import Controlador.ControladorEdicionDocente;
import Controlador.ObtenerComponentes;
import Modelo.Docente;

/**
 *
 * @author varga
 */
public class EdicionDocente extends javax.swing.JFrame {

    /**
     * Creates new form EdicionDocente
     */
    ControladorEdicionDocente controlador;
    ObtenerComponentes chamba;
    ControladorDiseñoBoton desing;

    public EdicionDocente() {
        initComponents();
        chamba = new ObtenerComponentes();
        desing = new ControladorDiseñoBoton(chamba.obtenerBotones(jPanel1));
        controlador = new ControladorEdicionDocente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaApPaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboAño = new javax.swing.JComboBox<>();
        cajaApMaterno = new javax.swing.JTextField();
        etiquetaNoPlaza = new javax.swing.JLabel();
        etiquetaSexo = new javax.swing.JLabel();
        comboSexo = new javax.swing.JComboBox<>();
        cajaNoPlaza = new javax.swing.JTextField();
        guardarDocente = new javax.swing.JButton();
        etiquetaValidacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 400));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Nombre: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(100, 20, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        cajaNombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaNombre.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaNombre.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 10, 0);
        jPanel1.add(cajaNombre, gridBagConstraints);

        cajaApPaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaApPaterno.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaApPaterno.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(cajaApPaterno, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Apellido paterno: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("Apellido materno: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Año de nacimiento:");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        comboAño.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboAño.setMinimumSize(new java.awt.Dimension(180, 30));
        comboAño.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(comboAño, gridBagConstraints);

        cajaApMaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaApMaterno.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaApMaterno.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(cajaApMaterno, gridBagConstraints);

        etiquetaNoPlaza.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        etiquetaNoPlaza.setText("# Plaza:");
        etiquetaNoPlaza.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaNoPlaza.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaNoPlaza.setName("docente"); // NOI18N
        etiquetaNoPlaza.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 10, 0);
        jPanel1.add(etiquetaNoPlaza, gridBagConstraints);

        etiquetaSexo.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        etiquetaSexo.setText("Sexo:");
        etiquetaSexo.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaSexo.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaSexo.setName("alumno"); // NOI18N
        etiquetaSexo.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(etiquetaSexo, gridBagConstraints);

        comboSexo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboSexo.setMinimumSize(new java.awt.Dimension(180, 30));
        comboSexo.setName("licenciatura"); // NOI18N
        comboSexo.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        jPanel1.add(comboSexo, gridBagConstraints);

        cajaNoPlaza.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaNoPlaza.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaNoPlaza.setName("docente"); // NOI18N
        cajaNoPlaza.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 10, 0);
        jPanel1.add(cajaNoPlaza, gridBagConstraints);

        guardarDocente.setBackground(new java.awt.Color(84, 125, 174));
        guardarDocente.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        guardarDocente.setText("  Guardar");
        guardarDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        guardarDocente.setBorderPainted(false);
        guardarDocente.setContentAreaFilled(false);
        guardarDocente.setHideActionText(true);
        guardarDocente.setMaximumSize(new java.awt.Dimension(160, 50));
        guardarDocente.setMinimumSize(new java.awt.Dimension(160, 50));
        guardarDocente.setName("docente"); // NOI18N
        guardarDocente.setOpaque(true);
        guardarDocente.setPreferredSize(new java.awt.Dimension(160, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        jPanel1.add(guardarDocente, gridBagConstraints);

        etiquetaValidacion.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        etiquetaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaValidacion.setMaximumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setMinimumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 10, 0);
        jPanel1.add(etiquetaValidacion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void setDocente(Docente docente) {
        controlador.setDocente(docente);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionDocente().setVisible(true);
            }
        });
    }

    public void setPantallaPrincipal(PantallaPrincipal pantallaPrincipal) {
        controlador.setPantallaPrincipal(pantallaPrincipal);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cajaApMaterno;
    public javax.swing.JTextField cajaApPaterno;
    public javax.swing.JTextField cajaNoPlaza;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JComboBox<String> comboAño;
    public javax.swing.JComboBox<Object> comboSexo;
    public javax.swing.JLabel etiquetaNoPlaza;
    public javax.swing.JLabel etiquetaSexo;
    public javax.swing.JLabel etiquetaValidacion;
    public javax.swing.JButton guardarDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
