/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorDiseñoBoton;
import Controlador.ControladorEdicionAlumno;
import Controlador.ManejoBD;
import Controlador.ObtenerComponentes;
import Modelo.Alumno;

/**
 *
 * @author varga
 */
public class EdicionAlumno extends javax.swing.JFrame {

    /**
     * Creates new form EdicionAlumno
     */
    ControladorEdicionAlumno controlador;
    ControladorDiseñoBoton botond;
    ObtenerComponentes chamba;

    public EdicionAlumno() {
        initComponents();
        controlador = new ControladorEdicionAlumno(this);
        chamba = new ObtenerComponentes();
        botond = new ControladorDiseñoBoton(chamba.obtenerBotones(jPanel1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        cajaNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaApPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaApMaterno = new javax.swing.JTextField();
        comboAño = new javax.swing.JComboBox<>();
        etiquetaMatricula = new javax.swing.JLabel();
        etiquetaFacultad1 = new javax.swing.JLabel();
        etiquetaLicenciatura1 = new javax.swing.JLabel();
        etiquetaSexo = new javax.swing.JLabel();
        cajaMatricula = new javax.swing.JTextField();
        comboFacultad1 = new javax.swing.JComboBox<Object>();
        comboLicenciatura = new javax.swing.JComboBox<>();
        comboSexo = new javax.swing.JComboBox<>();
        guardarAlumno = new javax.swing.JButton();
        etiquetaLicenciatura2 = new javax.swing.JLabel();
        comboSemestre = new javax.swing.JComboBox<>();
        etiquetaValidacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(243, 224, 166));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        cajaNombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaNombre.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaNombre.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 10, 0);
        jPanel1.add(cajaNombre, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel1.setText("Nombre: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 20, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel2.setText("Apellido paterno: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        cajaApPaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaApPaterno.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaApPaterno.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(cajaApPaterno, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("Apellido materno: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel3.setText("Año de nacimiento:");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        cajaApMaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaApMaterno.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaApMaterno.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(cajaApMaterno, gridBagConstraints);

        comboAño.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboAño.setMinimumSize(new java.awt.Dimension(180, 30));
        comboAño.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(comboAño, gridBagConstraints);

        etiquetaMatricula.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        etiquetaMatricula.setText("Matrícula:");
        etiquetaMatricula.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaMatricula.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaMatricula.setName("alumno"); // NOI18N
        etiquetaMatricula.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 10, 0);
        jPanel1.add(etiquetaMatricula, gridBagConstraints);

        etiquetaFacultad1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        etiquetaFacultad1.setText("Facultad:");
        etiquetaFacultad1.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaFacultad1.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaFacultad1.setName("alumno"); // NOI18N
        etiquetaFacultad1.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(etiquetaFacultad1, gridBagConstraints);

        etiquetaLicenciatura1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        etiquetaLicenciatura1.setText("Licenciatura:");
        etiquetaLicenciatura1.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaLicenciatura1.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaLicenciatura1.setName("alumno"); // NOI18N
        etiquetaLicenciatura1.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(etiquetaLicenciatura1, gridBagConstraints);

        etiquetaSexo.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        etiquetaSexo.setText("Sexo:");
        etiquetaSexo.setMaximumSize(new java.awt.Dimension(150, 30));
        etiquetaSexo.setMinimumSize(new java.awt.Dimension(150, 30));
        etiquetaSexo.setName("alumno"); // NOI18N
        etiquetaSexo.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(etiquetaSexo, gridBagConstraints);

        cajaMatricula.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaMatricula.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaMatricula.setName("alumno"); // NOI18N
        cajaMatricula.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 10, 0);
        jPanel1.add(cajaMatricula, gridBagConstraints);

        comboFacultad1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboFacultad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboFacultad1.setMinimumSize(new java.awt.Dimension(180, 30));
        comboFacultad1.setName("alumno"); // NOI18N
        comboFacultad1.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        jPanel1.add(comboFacultad1, gridBagConstraints);

        comboLicenciatura.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboLicenciatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboLicenciatura.setMinimumSize(new java.awt.Dimension(180, 30));
        comboLicenciatura.setName("licenciatura"); // NOI18N
        comboLicenciatura.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        jPanel1.add(comboLicenciatura, gridBagConstraints);

        comboSexo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboSexo.setMinimumSize(new java.awt.Dimension(180, 30));
        comboSexo.setName("licenciatura"); // NOI18N
        comboSexo.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(comboSexo, gridBagConstraints);

        guardarAlumno.setBackground(new java.awt.Color(84, 125, 174));
        guardarAlumno.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        guardarAlumno.setText("  Guardar ");
        guardarAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        guardarAlumno.setBorderPainted(false);
        guardarAlumno.setContentAreaFilled(false);
        guardarAlumno.setHideActionText(true);
        guardarAlumno.setMaximumSize(new java.awt.Dimension(160, 50));
        guardarAlumno.setMinimumSize(new java.awt.Dimension(160, 50));
        guardarAlumno.setName("alumno"); // NOI18N
        guardarAlumno.setOpaque(true);
        guardarAlumno.setPreferredSize(new java.awt.Dimension(160, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        jPanel1.add(guardarAlumno, gridBagConstraints);

        etiquetaLicenciatura2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        etiquetaLicenciatura2.setText("Semestre:");
        etiquetaLicenciatura2.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaLicenciatura2.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaLicenciatura2.setName("alumno"); // NOI18N
        etiquetaLicenciatura2.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(etiquetaLicenciatura2, gridBagConstraints);

        comboSemestre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboSemestre.setMinimumSize(new java.awt.Dimension(180, 30));
        comboSemestre.setName("licenciatura"); // NOI18N
        comboSemestre.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        jPanel1.add(comboSemestre, gridBagConstraints);

        etiquetaValidacion.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        etiquetaValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaValidacion.setMaximumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setMinimumSize(new java.awt.Dimension(200, 30));
        etiquetaValidacion.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 10, 0);
        jPanel1.add(etiquetaValidacion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionAlumno().setVisible(true);
            }
        });
    }

    public void setAlumno(Alumno alumno) {
        controlador.setObjAlumno(alumno);
    }

    public void setPantallaPrincipal(PantallaPrincipal pantallaPrincipal) {
        controlador.setPantallaPrincipal(pantallaPrincipal);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cajaApMaterno;
    public javax.swing.JTextField cajaApPaterno;
    public javax.swing.JTextField cajaMatricula;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JComboBox<String> comboAño;
    public javax.swing.JComboBox<Object> comboFacultad1;
    public javax.swing.JComboBox<Object> comboLicenciatura;
    public javax.swing.JComboBox<Object> comboSemestre;
    public javax.swing.JComboBox<Object> comboSexo;
    public javax.swing.JLabel etiquetaFacultad1;
    public javax.swing.JLabel etiquetaLicenciatura1;
    public javax.swing.JLabel etiquetaLicenciatura2;
    public javax.swing.JLabel etiquetaMatricula;
    public javax.swing.JLabel etiquetaSexo;
    public javax.swing.JLabel etiquetaValidacion;
    public javax.swing.JButton guardarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
