/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorDiseñoBoton;
import Controlador.ControladorEdicionVisitante;
import Controlador.ManejoBD;
import Controlador.ObtenerComponentes;
import Modelo.Visitante;

/**
 *
 * @author varga
 */
public class EdicionVisitante extends javax.swing.JFrame {

    /**
     * Creates new form EdicionVisitante
     */
    ControladorDiseñoBoton dBoton;
    ObtenerComponentes chamba;
    ControladorEdicionVisitante controlador;

    public EdicionVisitante() {
        initComponents();
        chamba = new ObtenerComponentes();
        dBoton = new ControladorDiseñoBoton(chamba.obtenerBotones(jPanel1));
        controlador = new ControladorEdicionVisitante(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboAño = new javax.swing.JComboBox<>();
        cajaApMaterno = new javax.swing.JTextField();
        cajaApPaterno = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        etiquetaInstitucion = new javax.swing.JLabel();
        etiquetaSexo = new javax.swing.JLabel();
        comboInstitucion = new javax.swing.JComboBox<>();
        comboSexo = new javax.swing.JComboBox<>();
        guardarVisitante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(210, 231, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 400));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Nombre: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(100, 20, 10, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Apellido paterno: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("Apellido materno: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Año de nacimiento:");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        comboAño.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboAño.setMaximumSize(new java.awt.Dimension(250, 30));
        comboAño.setMinimumSize(new java.awt.Dimension(180, 30));
        comboAño.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(comboAño, gridBagConstraints);

        cajaApMaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaApMaterno.setMaximumSize(new java.awt.Dimension(250, 30));
        cajaApMaterno.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaApMaterno.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(cajaApMaterno, gridBagConstraints);

        cajaApPaterno.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaApPaterno.setMaximumSize(new java.awt.Dimension(250, 30));
        cajaApPaterno.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaApPaterno.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(cajaApPaterno, gridBagConstraints);

        cajaNombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        cajaNombre.setMaximumSize(new java.awt.Dimension(250, 30));
        cajaNombre.setMinimumSize(new java.awt.Dimension(180, 30));
        cajaNombre.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 10, 0);
        jPanel1.add(cajaNombre, gridBagConstraints);

        etiquetaInstitucion.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        etiquetaInstitucion.setText("Institución:");
        etiquetaInstitucion.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaInstitucion.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaInstitucion.setName("visitante"); // NOI18N
        etiquetaInstitucion.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 10, 0);
        jPanel1.add(etiquetaInstitucion, gridBagConstraints);

        etiquetaSexo.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        etiquetaSexo.setText("Sexo:");
        etiquetaSexo.setMaximumSize(new java.awt.Dimension(100, 30));
        etiquetaSexo.setMinimumSize(new java.awt.Dimension(100, 30));
        etiquetaSexo.setName("alumno"); // NOI18N
        etiquetaSexo.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(etiquetaSexo, gridBagConstraints);

        comboInstitucion.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboInstitucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboInstitucion.setMaximumSize(new java.awt.Dimension(250, 30));
        comboInstitucion.setMinimumSize(new java.awt.Dimension(180, 30));
        comboInstitucion.setName("visitante"); // NOI18N
        comboInstitucion.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 10, 0);
        jPanel1.add(comboInstitucion, gridBagConstraints);

        comboSexo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboSexo.setMinimumSize(new java.awt.Dimension(180, 30));
        comboSexo.setName("licenciatura"); // NOI18N
        comboSexo.setPreferredSize(new java.awt.Dimension(180, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        jPanel1.add(comboSexo, gridBagConstraints);

        guardarVisitante.setBackground(new java.awt.Color(84, 125, 174));
        guardarVisitante.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        guardarVisitante.setText("  Guardar");
        guardarVisitante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        guardarVisitante.setBorderPainted(false);
        guardarVisitante.setContentAreaFilled(false);
        guardarVisitante.setHideActionText(true);
        guardarVisitante.setMaximumSize(new java.awt.Dimension(160, 50));
        guardarVisitante.setMinimumSize(new java.awt.Dimension(160, 50));
        guardarVisitante.setName("visitante"); // NOI18N
        guardarVisitante.setOpaque(true);
        guardarVisitante.setPreferredSize(new java.awt.Dimension(160, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        jPanel1.add(guardarVisitante, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionVisitante().setVisible(true);
            }
        });
    }

    public void setVisitante(Visitante visitante) {
        controlador.setObjVisitante(visitante);
    }

    public void setManejoBD(ManejoBD manejo) {
        controlador.setManejoBD(manejo);
    }

    public void setPantallaPrincipal(PantallaPrincipal pantallaPrincipal) {
        controlador.setPantallaPrincipal(pantallaPrincipal);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cajaApMaterno;
    public javax.swing.JTextField cajaApPaterno;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JComboBox<String> comboAño;
    public javax.swing.JComboBox<Object> comboInstitucion;
    public javax.swing.JComboBox<Object> comboSexo;
    public javax.swing.JLabel etiquetaInstitucion;
    public javax.swing.JLabel etiquetaSexo;
    public javax.swing.JButton guardarVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
