/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author varga
 */
public class Historial extends javax.swing.JPanel {

    /**
     * Creates new form Historial2
     */
    public Historial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        etiquetaClave = new javax.swing.JLabel();
        cajaBuscarClave = new javax.swing.JTextField();
        cajaBuscarPor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        panelOpciones = new javax.swing.JPanel();
        botonEditar = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(196, 229, 174));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 200));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        etiquetaClave.setBackground(new java.awt.Color(32, 32, 32));
        etiquetaClave.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        etiquetaClave.setText("      Buscar ID:");
        etiquetaClave.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(etiquetaClave, gridBagConstraints);

        cajaBuscarClave.setBorder(null);
        cajaBuscarClave.setMinimumSize(new java.awt.Dimension(160, 30));
        cajaBuscarClave.setPreferredSize(new java.awt.Dimension(160, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(cajaBuscarClave, gridBagConstraints);

        cajaBuscarPor.setBorder(null);
        cajaBuscarPor.setMinimumSize(new java.awt.Dimension(160, 30));
        cajaBuscarPor.setPreferredSize(new java.awt.Dimension(160, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(cajaBuscarPor, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(32, 32, 32));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        jLabel2.setText("      Buscar por:");
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(196, 229, 174));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 350));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 350));

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "No.Registro", "Hora_Entrada", "Hora_salida", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonas.setRowHeight(50);
        jScrollPane1.setViewportView(tablaPersonas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        panelOpciones.setBackground(new java.awt.Color(196, 229, 174));
        panelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 0, 18), new java.awt.Color(240, 240, 240))), "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 0, 18))); // NOI18N
        panelOpciones.setForeground(new java.awt.Color(240, 240, 240));
        panelOpciones.setMinimumSize(new java.awt.Dimension(160, 350));
        panelOpciones.setPreferredSize(new java.awt.Dimension(160, 350));
        panelOpciones.setLayout(new java.awt.GridBagLayout());

        botonEditar.setBackground(new java.awt.Color(152, 219, 175));
        botonEditar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        botonEditar.setText("Finalizar");
        botonEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        botonEditar.setBorderPainted(false);
        botonEditar.setContentAreaFilled(false);
        botonEditar.setMinimumSize(new java.awt.Dimension(158, 50));
        botonEditar.setOpaque(true);
        botonEditar.setPreferredSize(new java.awt.Dimension(158, 50));
        botonEditar.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        panelOpciones.add(botonEditar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel2.add(panelOpciones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonEditar;
    public javax.swing.JTextField cajaBuscarClave;
    public javax.swing.JTextField cajaBuscarPor;
    public javax.swing.JLabel etiquetaClave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelOpciones;
    public javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables
}
