/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author varga
 */
import Controlador.ControladorDiseñoBoton;
import Controlador.ControladorHistorial;
import Controlador.ObtenerComponentes;
import Modelo.Sesion;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.JTableHeader;

public class Historial extends javax.swing.JPanel {

    /**
     * Creates new form Historial2
     */
    ControladorHistorial controlador;
    ControladorDiseñoBoton d;
    ObtenerComponentes c;

    public Historial() {
        initComponents();
        controlador = new ControladorHistorial(this);
        c = new ObtenerComponentes();
        d = new ControladorDiseñoBoton(c.obtenerBotones(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        kGradientPanel1 = new keeptoo.KGradientPanel();
        etiquetaClave = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaBuscarClave = new javax.swing.JTextField();
        cajaBuscarPor = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        panelOpciones = new javax.swing.JPanel();
        botonEditar = new javax.swing.JButton();
        botonDescargarExcel = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();

        setBackground(new java.awt.Color(84, 125, 174));
        setLayout(new java.awt.GridBagLayout());

        kGradientPanel1.setBackground(new java.awt.Color(210, 231, 255));
        kGradientPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel1.setkEndColor(new java.awt.Color(210, 231, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(210, 231, 255));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(120, 0));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(150, 0));

        etiquetaClave.setBackground(new java.awt.Color(32, 32, 32));
        etiquetaClave.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        etiquetaClave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaClave.setText("      Buscar ID:");
        etiquetaClave.setPreferredSize(new java.awt.Dimension(130, 30));

        jLabel2.setBackground(new java.awt.Color(32, 32, 32));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("      Buscar por:");
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 30));

        cajaBuscarClave.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        cajaBuscarClave.setBorder(null);
        cajaBuscarClave.setMinimumSize(new java.awt.Dimension(160, 30));
        cajaBuscarClave.setPreferredSize(new java.awt.Dimension(160, 30));

        cajaBuscarPor.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        cajaBuscarPor.setBorder(null);
        cajaBuscarPor.setMinimumSize(new java.awt.Dimension(160, 30));
        cajaBuscarPor.setPreferredSize(new java.awt.Dimension(160, 30));

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        fecha.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        panelOpciones.setBackground(new java.awt.Color(196, 229, 174));
        panelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 0, 18), new java.awt.Color(240, 240, 240))), "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 0, 18))); // NOI18N
        panelOpciones.setForeground(new java.awt.Color(240, 240, 240));
        panelOpciones.setMinimumSize(new java.awt.Dimension(160, 350));
        panelOpciones.setOpaque(false);
        panelOpciones.setPreferredSize(new java.awt.Dimension(160, 350));
        panelOpciones.setLayout(new java.awt.GridBagLayout());

        botonEditar.setBackground(new java.awt.Color(84, 125, 174));
        botonEditar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(255, 255, 255));
        botonEditar.setText("Finalizar");
        botonEditar.setBorder(null);
        botonEditar.setBorderPainted(false);
        botonEditar.setContentAreaFilled(false);
        botonEditar.setMinimumSize(new java.awt.Dimension(150, 40));
        botonEditar.setOpaque(true);
        botonEditar.setPreferredSize(new java.awt.Dimension(147, 40));
        botonEditar.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelOpciones.add(botonEditar, gridBagConstraints);

        botonDescargarExcel.setBackground(new java.awt.Color(84, 125, 174));
        botonDescargarExcel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        botonDescargarExcel.setForeground(new java.awt.Color(255, 255, 255));
        botonDescargarExcel.setText("Descargar");
        botonDescargarExcel.setBorder(null);
        botonDescargarExcel.setContentAreaFilled(false);
        botonDescargarExcel.setMinimumSize(new java.awt.Dimension(150, 40));
        botonDescargarExcel.setOpaque(true);
        botonDescargarExcel.setPreferredSize(new java.awt.Dimension(147, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelOpciones.add(botonDescargarExcel, gridBagConstraints);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaClave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaBuscarPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cajaBuscarClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(etiquetaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cajaBuscarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(kGradientPanel1, gridBagConstraints);

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.setkEndColor(new java.awt.Color(210, 231, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(210, 231, 255));
        kGradientPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 350));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 350));

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "No.Registro", "Hora_Entrada", "Hora_salida", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonas.setRowHeight(50);
        tablaPersonas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaPersonas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTableHeader header = tablaPersonas.getTableHeader();
        header.setFont(new Font("Microsoft JhengHei", Font.BOLD, 18)); 
        header.setBackground(new Color(84,125,174));             
        header.setForeground(Color.BLACK);
        header.setOpaque(true);
        jScrollPane1.setViewportView(tablaPersonas);
        if (tablaPersonas.getColumnModel().getColumnCount() > 0) {
            tablaPersonas.getColumnModel().getColumn(0).setResizable(false);
            tablaPersonas.getColumnModel().getColumn(1).setResizable(false);
            tablaPersonas.getColumnModel().getColumn(2).setResizable(false);
            tablaPersonas.getColumnModel().getColumn(3).setResizable(false);
            tablaPersonas.getColumnModel().getColumn(4).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        kGradientPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(kGradientPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
public void llenarTabla(ArrayList<Sesion> sesiones) {
        controlador.llenarTabla(sesiones);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonDescargarExcel;
    public javax.swing.JButton botonEditar;
    public javax.swing.JTextField cajaBuscarClave;
    public javax.swing.JTextField cajaBuscarPor;
    public javax.swing.JLabel etiquetaClave;
    public com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel panelOpciones;
    public javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables
}
