/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author varga
 */
public class IngresoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form IngresoUsuario
     */
    public IngresoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        etiquetaMatricula = new javax.swing.JLabel();
        cajaMatricula = new javax.swing.JTextField();
        comboPersona = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonInicioSesion = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(196, 229, 174));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 200));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        etiquetaMatricula.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        etiquetaMatricula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaMatricula.setText("Matrícula:");
        etiquetaMatricula.setMaximumSize(new java.awt.Dimension(90, 30));
        etiquetaMatricula.setMinimumSize(new java.awt.Dimension(90, 30));
        etiquetaMatricula.setPreferredSize(new java.awt.Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(etiquetaMatricula, gridBagConstraints);

        cajaMatricula.setMaximumSize(new java.awt.Dimension(100, 30));
        cajaMatricula.setMinimumSize(new java.awt.Dimension(100, 30));
        cajaMatricula.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(cajaMatricula, gridBagConstraints);

        comboPersona.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        comboPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente", "Visitante" }));
        comboPersona.setMinimumSize(new java.awt.Dimension(150, 30));
        comboPersona.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(comboPersona, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(196, 229, 174));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(196, 229, 174));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO");
        jLabel2.setMaximumSize(new java.awt.Dimension(720, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(720, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(720, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("...");
        jLabel1.setMaximumSize(new java.awt.Dimension(720, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(720, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(720, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jLabel1, gridBagConstraints);

        botonInicioSesion.setBackground(new java.awt.Color(60, 76, 143));
        botonInicioSesion.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        botonInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonInicioSesion.setText("Iniciar sesion");
        botonInicioSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 154, 3)));
        botonInicioSesion.setBorderPainted(false);
        botonInicioSesion.setContentAreaFilled(false);
        botonInicioSesion.setMinimumSize(new java.awt.Dimension(158, 50));
        botonInicioSesion.setOpaque(true);
        botonInicioSesion.setPreferredSize(new java.awt.Dimension(158, 50));
        botonInicioSesion.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel2.add(botonInicioSesion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonInicioSesion;
    public javax.swing.JTextField cajaMatricula;
    public javax.swing.JComboBox<String> comboPersona;
    public javax.swing.JLabel etiquetaMatricula;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
