/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorPantallaPrincipal;
import Vista.ClasesEspeciales.SideMenuPanel;
import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author varga
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public SideMenuPanel sp;
    public CardLayout vistaDinamica;
    private ControladorPantallaPrincipal controlador;

    public PantallaPrincipal() {
        initComponents();
        sp = new SideMenuPanel(this);
        sp.setMain(panelDinamico);
        sp.setSide(sidebar);
        sp.setMinWidth(55);
        sp.setMaxWidth(120);
        sp.setMainAnimation(false);
        sp.setSpeed(4);
        sp.setResponsiveMinWidth(600);
        vistaDinamica = (CardLayout) panelDinamico.getLayout();
        controlador = new ControladorPantallaPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        sidebar = new keeptoo.KGradientPanel();
        btnMenu = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnHogar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnHogar1 = new javax.swing.JButton();
        btnHogar2 = new javax.swing.JButton();
        btnHogar3 = new javax.swing.JButton();
        panelDinamico = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        sidebar.setkEndColor(new java.awt.Color(46, 78, 121));
        sidebar.setkStartColor(new java.awt.Color(84, 125, 174));
        sidebar.setMinimumSize(new java.awt.Dimension(55, 0));
        sidebar.setPreferredSize(new java.awt.Dimension(55, 0));

        btnMenu.setBackground(new java.awt.Color(84, 125, 174));
        btnMenu.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/menu_25dp_FFFFFF_FILL0_wght400_GRAD-25_opsz24.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setHideActionText(true);
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenu.setIconTextGap(20);
        btnMenu.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnMenu.setMinimumSize(new java.awt.Dimension(0, 0));
        btnMenu.setPreferredSize(new java.awt.Dimension(50, 574));
        btnMenu.setRolloverEnabled(false);

        btnAlta.setBackground(new java.awt.Color(84, 125, 174));
        btnAlta.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/person_add_25dp_E3E3E3_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnAlta.setText("ALTAS");
        btnAlta.setBorderPainted(false);
        btnAlta.setContentAreaFilled(false);
        btnAlta.setHideActionText(true);
        btnAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAlta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlta.setIconTextGap(20);
        btnAlta.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnAlta.setMinimumSize(new java.awt.Dimension(0, 0));
        btnAlta.setPreferredSize(new java.awt.Dimension(50, 574));
        btnAlta.setRolloverEnabled(false);

        btnHogar.setBackground(new java.awt.Color(84, 125, 174));
        btnHogar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnHogar.setForeground(new java.awt.Color(255, 255, 255));
        btnHogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/home_25dp_E3E3E3_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnHogar.setText("HOGAR");
        btnHogar.setBorderPainted(false);
        btnHogar.setContentAreaFilled(false);
        btnHogar.setHideActionText(true);
        btnHogar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHogar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHogar.setIconTextGap(20);
        btnHogar.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnHogar.setMinimumSize(new java.awt.Dimension(0, 0));
        btnHogar.setPreferredSize(new java.awt.Dimension(50, 574));
        btnHogar.setRolloverEnabled(false);

        btnConsulta.setBackground(new java.awt.Color(84, 125, 174));
        btnConsulta.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/person_search_25dp_E3E3E3_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnConsulta.setText("CONSULTA");
        btnConsulta.setBorderPainted(false);
        btnConsulta.setContentAreaFilled(false);
        btnConsulta.setHideActionText(true);
        btnConsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsulta.setIconTextGap(20);
        btnConsulta.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnConsulta.setMinimumSize(new java.awt.Dimension(0, 0));
        btnConsulta.setPreferredSize(new java.awt.Dimension(50, 574));
        btnConsulta.setRolloverEnabled(false);

        jPanel2.setBackground(new java.awt.Color(84, 125, 174));
        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        btnHogar1.setBackground(new java.awt.Color(84, 125, 174));
        btnHogar1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnHogar1.setForeground(new java.awt.Color(255, 255, 255));
        btnHogar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/tab_search_25dp_E3E3E3_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnHogar1.setText("HISTORIAL");
        btnHogar1.setBorderPainted(false);
        btnHogar1.setContentAreaFilled(false);
        btnHogar1.setHideActionText(true);
        btnHogar1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHogar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHogar1.setIconTextGap(20);
        btnHogar1.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnHogar1.setMinimumSize(new java.awt.Dimension(0, 0));
        btnHogar1.setPreferredSize(new java.awt.Dimension(50, 574));
        btnHogar1.setRolloverEnabled(false);

        btnHogar2.setBackground(new java.awt.Color(84, 125, 174));
        btnHogar2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnHogar2.setForeground(new java.awt.Color(255, 255, 255));
        btnHogar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/table_chart_view_25dp_E3E3E3_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnHogar2.setText("REPORTES");
        btnHogar2.setBorderPainted(false);
        btnHogar2.setContentAreaFilled(false);
        btnHogar2.setHideActionText(true);
        btnHogar2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHogar2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHogar2.setIconTextGap(20);
        btnHogar2.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnHogar2.setMinimumSize(new java.awt.Dimension(0, 0));
        btnHogar2.setPreferredSize(new java.awt.Dimension(50, 574));
        btnHogar2.setRolloverEnabled(false);

        btnHogar3.setBackground(new java.awt.Color(84, 125, 174));
        btnHogar3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnHogar3.setForeground(new java.awt.Color(255, 255, 255));
        btnHogar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/id_card_25dp_E3E3E3_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnHogar3.setText("INGRESAR");
        btnHogar3.setBorderPainted(false);
        btnHogar3.setContentAreaFilled(false);
        btnHogar3.setHideActionText(true);
        btnHogar3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHogar3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHogar3.setIconTextGap(20);
        btnHogar3.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnHogar3.setMinimumSize(new java.awt.Dimension(0, 0));
        btnHogar3.setPreferredSize(new java.awt.Dimension(50, 574));
        btnHogar3.setRolloverEnabled(false);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addComponent(btnHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnHogar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHogar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHogar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHogar3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHogar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHogar2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(sidebar, gridBagConstraints);

        panelDinamico.setkEndColor(new java.awt.Color(200, 0, 100));
        panelDinamico.setkStartColor(new java.awt.Color(240, 240, 240));
        panelDinamico.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(panelDinamico, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlta;
    public javax.swing.JButton btnConsulta;
    public javax.swing.JButton btnHogar;
    public javax.swing.JButton btnHogar1;
    public javax.swing.JButton btnHogar2;
    public javax.swing.JButton btnHogar3;
    public javax.swing.JButton btnMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public keeptoo.KGradientPanel panelDinamico;
    private keeptoo.KGradientPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
